version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  neo4j:
    image: neo4j:4.2
    restart: unless-stopped
    volumes:
      - neo4j-data:/data 
    ports:
      - 7474:7474
      - 7687:7687


volumes:
  neo4j-data:
  postgres-data: 